version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - whisper
  whisper:
    image: ghcr.io/openai/whisper-asr-webservice:latest
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
      - ASR_PORT=9000
    restart: unless-stopped
    # Uncomment below to mount custom models
    # volumes:
    #   - ./models:/models
